feat: button component
CodeCrusader87/VirtualMall pull request #4
Opened 2024-03-11 13:13 UTC by Heavenlydawn

The primary and secondary variants for the button component have been added.

2024-03-11 14:51 UTC, zorro-ftw requested changes

2024-03-11 14:51 UTC, zorro-ftw commented on src/app/[locale]/page.tsx
> +	<Button text="Sign up" variant='secondary' />
Creating a component doesn't mean that you should integrate them to pages. Actually quite the opposite, you never integrate a component into another component/page in the same PR as you created them. Also, that's why we have the Storybook.

If you want to see how your component looks, you should create the story for it (stories.ts file) and run `npm run sb`.

Please remove these components from the page and create the story accordingly.

2024-03-11 14:51 UTC, zorro-ftw commented on src/Components/Buttons/Button.stories.ts
Why don't we have a story?

2024-03-11 14:57 UTC, Heavenlydawn commented on src/Components/Buttons/Button.stories.ts
Oh sorry I was to take that out
I don't completely understand how the storybook work just yet it's my first time using it but I'd figure it out
Thank you
I will fix it

2024-03-23 16:14 UTC, zorro-ftw approved these changes

2024-03-23 16:20 UTC, merged